"""empty message

Revision ID: 10c48c7e7526
Revises: 3a19b3b5d896
Create Date: 2014-02-14 22:58:36.297509

"""

# revision identifiers, used by Alembic.
revision = '10c48c7e7526'
down_revision = '3a19b3b5d896'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('api_token', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'api_token')
    ### end Alembic commands ###
