"""empty message

Revision ID: 2268227deebb
Revises: None
Create Date: 2014-02-13 16:51:09.794989

"""

# revision identifiers, used by Alembic.
revision = '2268227deebb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reply', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reply', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('topic', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('topic', 'created',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('topic', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('topic', 'created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('topic', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reply', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reply', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
