"""empty message

Revision ID: 26dfc02ce3ff
Revises: 10c48c7e7526
Create Date: 2014-02-15 16:43:56.552255

"""

# revision identifiers, used by Alembic.
revision = '26dfc02ce3ff'
down_revision = '10c48c7e7526'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('felling_lucky', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'felling_lucky')
    ### end Alembic commands ###
