"""empty message

Revision ID: 276f5d7b1612
Revises: 26dfc02ce3ff
Create Date: 2014-02-15 22:16:23.234823

"""

# revision identifiers, used by Alembic.
revision = '276f5d7b1612'
down_revision = '26dfc02ce3ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_user_read_topic', 'read_topic', ['user_id', 'topic_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_user_read_topic', 'read_topic')
    ### end Alembic commands ###
