"""empty message

Revision ID: 3a19b3b5d896
Revises: 2268227deebb
Create Date: 2014-02-14 21:25:56.726301

"""

# revision identifiers, used by Alembic.
revision = '3a19b3b5d896'
down_revision = '2268227deebb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('css', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'css')
    ### end Alembic commands ###
